### ISSUE TITLE
Will Document inheritance be supported?

### ISSUE THREAD

**Issue by OfirKP** [roman-right/beanie#116]
First of all, I have to say this library is concise and beautiful, and I'm happy I stumbled upon it!

I wondered if Document inheritance will be supported in the future, such as in [mongoengine](https://docs.mongoengine.org/guide/defining-documents.html#document-inheritance).
The problem arises when I have documents with mostly similar fields and some other varying fields, and in the corresponding algorithmic code in the backend, I got a representation of the same data with object inheritance. 

When I subclass a Document class (and set the same collection name), no error is thrown, but when I try to use the find_all() method on a base Document class, all of the child documents are projected onto the base class representation. I'd like to have a find function that would return all of the documents in their corresponding children Document classes.

My current workaround is using a single class definition along with a Union[] field that unifies different classes that represent "extra fields" on the single document.

**Comment by roman-right** [comment]
Hey @OfirKP ,

Thank you for the issue and good words about Beanie.

If I understood you correctly, projections can help you here.

Full working example:

```python
import asyncio
import motor.motor_asyncio

from beanie import Document, init_beanie


class BaseSample(Document):
    s: str

    class Collection:
        name = "test"


class Sample(BaseSample):
    i: int


async def main():
    uri = "YOUR_URI"
    cli = motor.motor_asyncio.AsyncIOMotorClient(uri)
    await init_beanie(cli.test_projection,
                      document_models=[BaseSample, Sample])
    await Sample(s="test1", i=100).insert()
    
    docs = await BaseSample.find(
        BaseSample.s == "test1"
    ).project(
        Sample
    ).to_list()
    
    print(docs)


asyncio.run(main())
```

Docs could be found here: 
https://roman-right.github.io/beanie/tutorial/finding-documents/#projections

**Comment by OfirKP** [comment]
Thank you for the quick response!

It's really nice to know that projections also have the downcasting notion (from BaseSample to Sample), but what I meant relates to multiple subclasses.

Let's say this is our case:
```python3
class BaseSample(Document):
    s: str

    class Collection:
        name = "test"


class Sample1(BaseSample):
    i: int


class Sample2(BaseSample):
    j: int
```

What I want is a way to retrieve a list of both Sample1 & Sample2 objects from the 'test' collection.
Maybe even allow projecting to a BaseItem like in https://github.com/samuelcolvin/pydantic/issues/503#issuecomment-906439127.

Can you think of a possible workaround for this situation?

**Comment by OfirKP** [comment]
My current approach is using one Document with a union of children for the "extra" properties:

```python3
class BaseSample(Document):
    s: str
    extra_params: Union[Sample1, Sample2]

    class Collection:
        name = "test"


class Sample1(BaseModel):
    i: int


class Sample2(BaseModel):
    j: int
```

It works, but I wonder if there's a better way.

**Comment by roman-right** [comment]
Hm. I think your implementation is the best, what I can suggest for now for this case. 
I'll think about dynamic structures - will take a look, how it is implemented in MongoEngine
Interesting case, thank you!

**Comment by j-riebe** [comment]
Hey @roman-right, 

first of all, this seems like an awesome project and I'm considering to migrate from mongoengine.
The tipping point for me is document inheritance.
Don't know if you had time to look into it yet, which is why I thought, I'd try to speed up your search, just in case.


As per the [docs](https://docs.mongoengine.org/guide/defining-documents.html#document-inheritance):

> Behind the scenes, MongoEngine deals with inheritance by adding a `_cls` attribute that contains the class name in every documents. When a document is loaded, MongoEngine checks it’s `_cls` attribute and use that class to construct the instance
> ``` 
>    # Stored in a collection named 'page'
>    class Page(Document):
>       title = StringField(max_length=200, required=True)
>       meta = {'allow_inheritance': True}
>
>    # Also stored in the collection named 'page'
>    class DatedPage(Page):
>        date = DateTimeField()
>
>    Page(title='a funky title').save()
>    DatedPage(title='another title', date=datetime.utcnow()).save()
>
>    print(Page.objects().count())         # 2
>    print(DatedPage.objects().count())    # 1
>    # print documents in their native form
>    # we remove 'id' to avoid polluting the output with unnecessary detail
>    qs = Page.objects.exclude('id').as_pymongo()
>    print(list(qs))
>    # [
>    #   {'_cls': u 'Page', 'title': 'a funky title'},
>    #   {'_cls': u 'Page.DatedPage', 'title': u 'another title', 'date': datetime.datetime(2019, 12, 13, 20, 16, 59, 993000)}
>    # ]```

Inheritance is controlled by two fields in the `meta` dict: `allow_inheritance` and `abstract`. 
At least one of them must be `True` otherwise an exception is raised during model registration if a `Document` is subclassed. 

As you can see above, `mongoengine` stores all non-abstract superclasses dot-separated inside a `_cls` field (e.g. `Page.DatedPage.AnyOtherSubPage.XXX`). 
A list of possible `_subclasses` / `_superclasses` for a type seems to be populated during model registration.
Inherited documents can only inherit from one non-abstract document that is mentioned in `_cls`, so there is no multiple inheritance in the sense.

You could populate private sub-/superclasses attributes of the inner `Config` during `init_beanie`.

Queries on specific classes are internally enriched with an `$in` statement including all registered subclasses.

E.g.
```
Page.objects.filter(query)
DatedPage.objects.filter(query)
```
translates to
```
{**query, "_cls": {"$in": ["Page", "Page.DatedPage"]}}
{**query, "_cls": {"$in": ["Page.DatedPage"]}}
```

During model parsing, you could again make use of the registered subclasses to determine the model type based on the `_cls` field.

https://github.com/roman-right/beanie/blob/ab0cf83346f630e1fa78d3614cc52ba26f96aab7/beanie/odm/utils/parsing.py#L9-L14

E.g. sth. like 

```python
def parse_obj( 
     model: Union[Type[BaseModel], Type["Document"]], data: Any 
 ) -> BaseModel: 
+    if hasattr(model.Config, "_subclasses") and "_cls" in data:
+       cls = data["_cls"].split(".")[-1]
+       model = model.Config._subclasses.get(cls)
     if hasattr(model, "_parse_obj_saving_state"): 
         return model._parse_obj_saving_state(data)  # type: ignore 
     return model.parse_obj(data) 
```
