### ISSUE TITLE
Not possible to use custom type for _id field

### ISSUE THREAD

**Issue by paul-nameless** [roman-right/beanie#12]
Something like this does't work:
```
class Task(Document):
    id: str = Field(..., alias="_id")
    updated: datetime = Field(..., default_factory=datetime.utcnow)
```

It would be cool to be able to set _id manually.

**Comment by roman-right** [comment]
Hi @paul-nameless ,

`_id` field itself is reserved by MongoDB to be used as a primary key. Typically it uses ObjectId for this. Correct me, if I'm wrong. Do you mean it would be useful to be able to use other data types for this primary key, right? Or are you talking about another use case?

**Comment by paul-nameless** [comment]
To be fear it's not reserved, it's required https://docs.mongodb.com/manual/reference/bson-types/#objectid

_id is often used as non ObjectId type as a "free" unique index, which doesn't require additional index setup, disk space and memory. This is quite crucial for big collections. 

So that would be great to make it more flexible

**Comment by roman-right** [comment]
First of all, thank you :-) I'm happy that it is useful.

I see. Yes, I do agree, it would be better to have this more flexible. This is linked with some internal logic and, unfortunately, it is impossible to replace it on the move fast. But I will put this improvement at the top of the backlog and will pick it up after the current major update.

Thank you.

**Comment by paul-nameless** [comment]
Basically, something like this let autogenerate _id if it's not set and use the given value otherwise.

https://github.com/paul-nameless/beanie/commit/7d4d78c83b86382e40d6476d8e8570cd20cfc540

That's just draft, if you don't see any issues and happy with this, I could continue working on it.

**Comment by roman-right** [comment]
Yes, this will partially work

The idea of this check is to understand if the document was already inserted or not. Bc if it was inserted, it will not be inserted again - the driver will just ignore the operation. It will not update anything and will not even warn, as I remember, about the double insert attempt. This can confuse. That's why there are two methods `create` to insert the document and `replace` for the full update.

There are some ways, how to solve this using custom id types: 
- A document can have an additional flag, like `_is_inserted` to manage these states. It must be hidden (protected). It will not protect from all the possible collisions, but most of them will be avoided. 
- `create()` method can check if the document with this id was already inserted into the database. It will solve all the collisions, but also it will increase the number of calls.
- Probably smth else, I didn't think well about this.

I prefer the first one for now. 

So yes, if you want to develop this feature - you are welcome for sure :-) 
If you want to chat about any details, you can do it in discord. The link is in the project readme
