### ISSUE TITLE
Error with type checking on sort in PyCharm

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#208]
Hi. Using the documented mode of sorting `sort(Class.field)` results in a warning in PyCharm. Is something off in the type definition. It seems to work fine.

<img width="690" alt="Screen Shot 2022-02-17 at 5 28 01 PM" src="https://user-images.githubusercontent.com/2035561/154600174-d4e37588-55a7-47fd-9740-c7b4038dd0bc.png">

**Comment by zrothberg** [comment]
pydantic autocasts So if you pass an int it will get converted into a string.

**Comment by mikeckennedy** [comment]
Thanks @zrothberg I do know that to be true. But my issue is that whatever the type declaration is, it is making PyCharm think that value usage is an error. 

```
Expected type 'str | tuple ...', got 'int' instead
```

I was hoping the type definition could be updated to include whatever is needed to make this line that works correctly appear without warnings.

**Comment by zrothberg** [comment]
I would avoid editing the library to do this if its not needed. I am presuming you are using the pydantic plugin. [It has a feature for parsable types. ](https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/) That tends to get rid of any of the highlighting issues.

**Comment by mikeckennedy** [comment]
I agree that changing the library should be done as little as possible. But I am using the latest version of PyCharm and have the Pydantic plugin installed and this is still showing as an error (under the warning category).

It is either a bug in PyCharm or a bug in Beanie.

**Comment by zrothberg** [comment]
Sorry I wasn't clear. The feature isn't on by default the plugin requires you to configure it. Beanies and Pydantics docs do not cover this but you need to set the pyproject.toml file with custom flags for the plugin in order for the plugin and duck typing to play nicely together. The other flag you need to set is `ignore-init-method-arguments = true` otherwise pycharm scarfs the init params for beanie because of inheritance. If those are not working then its a bug somewhere in the code that's casting that isn't being accounted for.

**Comment by mikeckennedy** [comment]
Ah got it. Thank you @zrothberg But what does the Pydantic plugin have to do with Beanie's `sort` method? This isn't affecting the constructor of the data model class, it's just the call to `sort`.

**Comment by zrothberg** [comment]
The function underneath is actually a class I am presuming you are asking about query. (I believe for async reasons) But looking [at the enum definition](https://github.com/roman-right/beanie/blob/main/beanie/odm/enums.py ). It is of type int, enum. 

I am actually very confused right now. You are using the class level show_id correct not the instance level one? That shouldn't be an integer either. Can you post your class definition? There may be a different kind of bug here. I think it's actually on a [return definition from fields](https://github.com/roman-right/beanie/blob/main/beanie/odm/fields.py) which does not have it marked as a fixed Enum which may be pycharms complaint.

**Comment by mikeckennedy** [comment]
Thanks. As I look at this closer, I believe it's an error with PyCharm, probably. So I filed a bug there:

https://youtrack.jetbrains.com/issue/PY-53582

@pauleveritt do you have any ideas what's happening here?

**Comment by pauleveritt** [comment]
I know you mentioned mypy above, did you ever run mypy to see if it got it right?

This is going to be a mashup of PyCharm, the pydantic plugin, pydantic, and Beanie so ouchies. I wonder if the error could be recreated in just a pydantic model without inheriting from `beanie.Document`.

Sometimes Python's run-time dynamics is more of a curse than blessing, eh? 😀

**Comment by zrothberg** [comment]
So the issue as far as I can tell is in part because of the pydantic plugin. Normal Pydantic classes do not have a class variable. Beanie follows a few other libs and uses a custom one. Most things get trimmed off of it within pycharm. So it just guessing the return type `__neg__ :int ` __neg__ has actually been modified in the field definition to  return a `tuple[str, SortDirection]` Theres is a lot of issues specifically working with class variables and beanie. I haven't been able to work around it. The problem really is from pydantic. 

Second to that. Beanie didn't declare a return signature in the above file. Sometimes pycharm infers them but it wasn't written in so 50/50 odds. But even if it gets added I am 99% sure it won't come through. Normally if I run into an issue like this I will just sometimes shove a type hint in there. And pycharm will figure it out. 

@mikeckennedy you should be able to test it by editing the code locally in the above linked file at 116 to include the return type. If it doesn't come through for you try disabling the plugin and seeing if it works. That will at least determine which system is pulling. I am away from my computer right now but when I get home tomorrow I can test it and narrow it down.

**Comment by mikeckennedy** [comment]
Thanks @zrothberg and @pauleveritt. It looks like the PyCharm team [might be open to](https://youtrack.jetbrains.com/issue/PY-53582) adding special support for Beanie types and the framework. That would be great. 

It's cool that `__neg__` has a special return type, but I don't know how to get it to transform the ascending sort (no modifiers) without PyCharm just knowing more about Beanie documents.

I'll close this issue. Thanks both of you for your thoughts.

**Comment by roman-right** [comment]
> Thanks @zrothberg and @pauleveritt. It looks like the PyCharm team [might be open to](https://youtrack.jetbrains.com/issue/PY-53582) adding special support for Beanie types and the framework. That would be great.
> 
> It's cool that `__neg__` has a special return type, but I don't know how to get it to transform the ascending sort (no modifiers) without PyCharm just knowing more about Beanie documents.
> 
> I'll close this issue. Thanks both of you for your thoughts.

Wow! What a great discussion you guys have here!
If PyCharm devs will need my help, I'm in. Beanie supporting there would be awesome!

**Comment by zrothberg** [comment]
@pauleveritt @mikeckennedy so apologize I actually misspoke here. There is an actual bug in pycharm it doesn't seem to care about the actual implied rules of type hints. Particularly it will take whatever type hint is given to the class and use that for the class variable type. Those are meant to be instance variable type references not class level. What is happening is that pycharm is claiming the call is coming from int which it is not.  

```__neg__``` on an int is an int. https://peps.python.org/pep-0681/ is the PEP designed to take care of signaling for these problems as far as I know only VScode supports it.

**Comment by pauleveritt** [comment]
@zrothberg Can you provide a simple, reproducible example we can file a bug report with?

**Comment by zrothberg** [comment]
<img width="599" alt="Screen Shot 2022-06-23 at 9 51 27 PM" src="https://user-images.githubusercontent.com/13908315/175446588-d550ef27-073a-4751-9d84-359cb1bc2cd5.png">

So for the first example pycharm is erroneously taking type hints defined at the class level to be class variable type hint. The way type hints are defined in python if it doesn't have the ClassVar Class around it the hint is supposed to be interpreted as the instance attribute type not the class attribute type. Because there is no init method pycharm never recognizes that the attribute is recreated on an instance level and just guesses it is a class variable. This is technically true but its a purely an implementation detail. On the class level the type should be whatever is actually set to the field so if it is name = 100. The type would be int not str regardless of the hint. The type hint that is given is meant to imply that at an instance level the type is str regardless of if it defined in self or not. 

<img width="599" alt="Screen Shot 2022-06-23 at 9 52 39 PM" src="https://user-images.githubusercontent.com/13908315/175446587-ecb983e0-a0a1-44e6-a11e-f06545978af8.png">

If you define an init method pycharm correctly knows that the attribute was redefined on the instance level and the inspection confirms this. 
https://peps.python.org/pep-0526/#class-and-instance-variable-annotations

That covers the intention of type hints. 

It gets very problematic when the type hints are defined in stubfiles as they are just wrong every time. Since they have no __init__ there is no possible way to correct the behavior. Below is a screen shot from the boto3 stub files its taking a attribute defined as a instance attribute and stating its a class attribute as far as I know it wouldn't even exist on the class level and that would be an unreachable namespace. It shouldn't even exist it should return nothing. 

<img width="722" alt="Screen Shot 2022-06-23 at 10 11 40 PM" src="https://user-images.githubusercontent.com/13908315/175448548-d3e29feb-d707-4b2d-82ee-d7247963c70c.png">

**Comment by roman-right** [comment]
Thank you, @pauleveritt

**Comment by zrothberg** [comment]
@pauleveritt I dont think it does. I am actually just noticing how many fully erroneous errors this makes. Take for example the Request class in urllib.request 

Pycharm falls back to typeshed which properly marks the field origin_req_host as a instance attribute. Pycharm won't warn against attempts to access it from the class. But the code will fail 100% of the time because of it simply does not exist. 

```py
from urllib.request import Request
print(Request.origin_req_host) #drop dead on the spot
```

Here is the typeshed for that class

```py
class Request:
    @property
    def full_url(self) -> str: ...
    @full_url.setter
    def full_url(self, value: str) -> None: ...
    @full_url.deleter
    def full_url(self) -> None: ...
    type: str
    host: str
    origin_req_host: str
    selector: str
    data: bytes | None
    headers: dict[str, str]
    unredirected_hdrs: dict[str, str]
    unverifiable: bool
    method: str | None
    timeout: float | None  # Undocumented, only set after __init__() by OpenerDirector.open()
    def __init__(
        self,
        url: str,
        data: bytes | None = ...,
        headers: dict[str, str] = ...,
        origin_req_host: str | None = ...,
        unverifiable: bool = ...,
        method: str | None = ...,
    ) -> None: ...
    def get_method(self) -> str: ...
    def add_header(self, key: str, val: str) -> None: ...
    def add_unredirected_header(self, key: str, val: str) -> None: ...
    def has_header(self, header_name: str) -> bool: ...
    def remove_header(self, header_name: str) -> None: ...
    def get_full_url(self) -> str: ...
    def set_proxy(self, host: str, type: str) -> None: ...
    @overload
    def get_header(self, header_name: str) -> str | None: ...
    @overload
    def get_header(self, header_name: str, default: _T) -> str | _T: ...
    def header_items(self) -> list[tuple[str, str]]: ...
    def has_proxy(self) -> bool: ...

```

It clearly labels the value as being an instance variable but because the hint is coming in the class body instead of inside __init__ (which do not get defined for stub files) Pycharm erroneously believes it is a class variable. 

I presume the issue is due to the way class vs functions vs module typehints are handled in python in that there definition scoping is not equivalent. Class have there own rules that only applies to them. The current behavior works correctly for functions and for module level definitions just not for class body ones.
