### ISSUE TITLE
Custom collection name is ignored

### ISSUE THREAD

**Issue by wuxmax** [roman-right/beanie#276]
Hello!

I try to specify a custom collection name via the `Settings` subclass:

```
class ProcessedEmail(Document):
    class Settings:
        name = "processed_emails"
    ...
```

But this gets ignored. Instead the collection `ProcessedEmail` is created/used.

I am using `beanie 1.8.10`

**Comment by wuxmax** [comment]
As I was wondering why was not using `beanie 1.11.0` (latest version at this moment), I realized that I still had `odmantic` in my requirements (another async pydantic-integrated ODM for MongoDB) as I was using it before. Removing this dependencies and rebuilding the project did the trick.

**Comment by roman-right** [comment]
Hi. Yes, this was a breaking change of 1.11. I have to support docs for different versions but didn't find time to make it well yet.

For 1.8.x you should use the `Collection` inner class to configure the collection name (with the field `name`). Till 1.11 It had 2 Inner classes for configs `Collection` and `Settings`. Since 1.11 everything is inside `Settings`
