### ISSUE TITLE
Relationship (Link) unloaded after update

### ISSUE THREAD

**Issue by miloops** [roman-right/beanie#309]
When calling `update()` related model is not loaded anymore:

```
    project = await Project.get(id, fetch_links=True)
    update_query = {"$set": {field: value for field, value in req.items()}}
    await project.update(update_query)
    return ProjectResponse(**project.dict())
```

Will result in an error:

```
E   pydantic.error_wrappers.ValidationError: 1 validation error for ProjectResponse
E   project_developer
E     value is not a valid dict (type=type_error.dict)
```

Debugging exposes the problem:

```
ipdb> project.project_developer
<beanie.odm.fields.Link object at 0x7f2a4c6d53f0>
```

A workaround is to add, after `update`:

```
await project.fetch_link(Project.project_developer)
```

**Comment by miloops** [comment]
@roman-right if this looks like a bug to you on beanie, I'm happy to work on a fix

**Comment by Vitalium** [comment]
I can confirm too, this behavior the same on the latest version 1.11.12.
After calling `.set()` (and therefore `update`) attribute of type Link or list of Links became contain `Link` objects instead of `Document`.

At odm/documents.py at line 156 there is for loop:
```python
        for key, value in dict(new_instance).items():
            setattr(self, key, value)
```

It can be changed to:
```python
        for key, value in dict(new_instance).items():
            setattr(self, key, value.fetch() if isinstance(Link) else value)
```

And we will achieve what we want in this particular case.

But the problem is deeper. What if the document was originally fetched without links?
I think that the Document object should store the way it was received from the database - whether fetch_link was used or not. Depending on this, synchronization must be performed after the update in one way or another.

**Comment by roman-right** [comment]
Hey @miloops ,
Sorry for the delay. It looks like a bug, yes. If you can pick it up, it would be great
