### ISSUE TITLE
Document.get with custom fields?

### ISSUE THREAD

**Issue by AmishNinja** [roman-right/beanie#48]
Hey! So first off: I'm digging Beanie a lot so far, and have been using it for a project. The entities that I'm using for this project, however, do not rely on the default `_id` unique id field of MongoDB and instead rely on a custom UUID for the API interface. So I was wondering what you thought about extending the Document.get method to be able to use _id by default, but also be able to perform find_one under the hood for alternate fields.

I'm able to work around it easily - I just use Entity.find_one( {"uuid": uuid} ) instead of Entity.get(uuid), where it presumes I mean to reference _id. You may think that it's a pretty niche use-case, and I'd probably agree with you, but overall I was still curious what you thought about making that aspect of Beanie more flexible.

Thanks!

**Comment by roman-right** [comment]
Hi @AmishNinja ,

I see. I will think about configuring the document to set up which field should be used in the get method. Probably in the inner class. Thank you for your feedback!

About your particular case. It looks like (I can be wrong, for sure), one of the new features can help you there. If you need just a UUID id and don't need ObjectId, you can set up a custom type for the document id.

Here is the example:

```python
from pydantic import Field
from uuid import UUID, uuid4


class Sample(Document):
    id: UUID = Field(default_factory=uuid4())
    name: str
```

This guy will use the UUID type instead of ObjectId for the id field, and it will automatically create uuid4 id on the Sample object initialization. Probably this will fit your case.

I'm happy, that Beanie is used in real projects :-) 
If you will face any issues, or just not comfortable things for your use case, please don't hesitate to share them. My own using scenarios are very limited by my projects. So, it helps a lot to see the overall picture and improve the development strategy.

Thank you for the inputs.
