### ISSUE TITLE
ElemMatch should support nested objects

### ISSUE THREAD

**Issue by mikeckennedy** [roman-right/beanie#498]
Hi @roman-right sorry if issue isn't the right format for this. Feel free to close it if you think it doesn't belong...

`ElemMatch` currently supports matching on a flat list, such as:

```python
ElemMatch(Sample.results, [80, 85])
# becomes
# {"results": {"$elemMatch": [80, 85]}}
```

But for work I'm doing, we have a list of embedded documents which is one of the primary reasons to use `elemMatch`. 

```python
class Release(pydantic.BaseModel):
    major_ver: int
    minor_ver: int
    build_ver: int

class Package(beanie.Document):
    releases: list[Release] = []
```
Then I want all packages with a certain version, say 7.1.0. I can do that like this now:

```python
count = await Package.find(
    ElemMatch(
        Package.releases,
        {"major_ver": 7, "minor_ver": 1, "build_ver": 0}
    )
).count()
```

But I think ElemMatch should support some way to do this without falling back to raw dictionaries (so things like "find usages" and refactoring work):

```python
count = await Package.find(
    ElemMatch(
        Package.releases,
        (Release.major_ver==7, Release.minor_ver==1, Release.build_ver==0)
    )
).count()

# raw mongo query:
# {'releases': {'$elemMatch': {'major_ver': 7, 'minor_ver': 1, 'build_ver': 0}}}
```

You could even keep it with dictionaries such as:

```python
count = await Package.find(
    ElemMatch(
        Package.releases,
        {Release.major_ver: 7, Release.minor_ver: 1, Release.build_ver: 0}
    )
).count()
```

**Comment by roman-right** [comment]
Hi Michael,
Sorry for the delay. On it

**Comment by roman-right** [comment]
The first problem I think I'm not able to solve nicely is that `Release` is a BaseModel class, which is not patched to call arguments on the class (non-instance) level and the magic methods (like __eq__) for it are also not patched. 
I see two ways to solve this:

- I can make an additional patched class for this case. Something like `Embedded` that will support the syntax like `Release.major_ver==7`. But you will have to use it instead of BaseModel: `class Release(beanie.Embedded):`
- I can accept arguments differently. This way: 
```python
ElemMatch(Package.releases, major_ver=7, minor_ver=1, build_ver=0)
```

I think the first option is better, as the syntax is more consistent there.

@mikeckennedy What do you think?

**Comment by mikeckennedy** [comment]
Hey @roman-right Thanks for thinking about this one. Both are interesting solutions.

As for having an EmbeddedDoc base class, I think I’d be fine with that. MongoEngine has something similar. On one hand, I think it would lead to a more consistent API. But I don’t know how much trouble/work it’ll cause for the larger codebase.

The second way looks good to me too. Although, at that point, it’s not adding much value beyond the dictionary variation I put in the description of issue.

So I guess my thoughts are if you’re 100% behind `beanie.Embedded`, that’s cool. But otherwise, maybe just close and tell me to use the dictionary version I’m already using. ;)
