### ISSUE TITLE
[BUG] datetime inconsistency after `insert()` and `get()`

### ISSUE THREAD

**Issue by joaquimcampos** [roman-right/beanie#513]
**Describe the bug**
There is an inconsistency in `datetime` fields between the return of `insert()` and `get()`.

**To Reproduce**
```
import asyncio
from datetime import datetime, timezone

from beanie import Document, init_beanie
from motor.motor_asyncio import AsyncIOMotorClient, AsyncIOMotorDatabase
from pydantic import Field


def datetime_func():
    return datetime.now(timezone.utc)


class Item(Document):
    s: str
    added_date: datetime = Field(default_factory=datetime_func)


async def main() -> None:
    cli = AsyncIOMotorClient("mongodb://beanie:beanie@localhost:27017")
    db = cli["test_id"]
    await init_beanie(
        database=db,
        document_models=[Item]  # type: ignore
    )

    item = Item(s="string")
    item_db = await item.insert()
    print(item_db.added_date)

    item_db = await Item.get(item_db.id)
    print(item_db.added_date)

    await cli.drop_database(db)

asyncio.run(main())
```

**Output**:
```
2023-03-23 13:24:56.166351+00:00
2023-03-23 13:24:56.166000
```

**Expected behavior**
Same `datetime` for both prints

**Comment by sabattle** [comment]
Experiencing the same issue

A couple more notes:
- not present in 1.17.0 and lower
- doesn't seem to be a problem with the `get` function, as the data is being inserted into MongoDB with the milliseconds truncated. The reason why the first item in the above example isn't truncated is because `insert` doesn't appear to return the inserted document. Instead it takes the same python object and assigns the newly created `ObjectId` to the `id` field

perhaps this is related to pymongo?

**Comment by IterableTrucks** [comment]
This problem also exists in 1.15.5
