### ISSUE TITLE
[improvement] Fix Indexed for type checkers

### ISSUE THREAD

**Issue by jorants** [roman-right/beanie#59]
MyPy (rightfully) complains that `Indexed(type)` should be `Indexed[]`.
This leaves two questions:
 - Can we come up with a nice syntax for the other arguments for Indexed
 - How do we do this under the hood. [__class_getitem__](https://docs.python.org/3/reference/datamodel.html#object.__class_getitem__) is designed for this, and might work if we only cared about mypy, but pydantic also needs to understand what is going on. Maybe a custom Pydantic type?

**Comment by roman-right** [comment]
Yes, good point.
Seems like this guy is relevant for the problem: https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types

**Comment by jorants** [comment]
Yes, and maybe the implementation of [Generic](https://github.com/python/cpython/blob/0729694246174a5c2f0ae197f2e0dbea61b90c9f/Lib/typing.py#L1227). I think it should be doable for the easiest use but I do not see an easy solution for the parameters to `Indexed`. Something like `Indexed(ASCENDING)[int]` might work but seems rather ugly. Including them  in the `[]` would break typing again.

**Comment by gpkc** [comment]
Hi, this is still happening. I guess the current workaround is to use `indexes` in the `Settings` class.

One question, wouldn't it be possible to use the assign syntax instead of typing? Just like Pydantic does with the `Field` function. So it could look like:

```python
class MyModel(Document, BaseModel):
    indexed: str = Indexed(...)
```

Is there any static advantage to having the `Indexed` type? For example, the `Optional` type is useful because it gives a static semantic for variables that can be `None`.

Of course, in the case of Pydantic, types also give important runtime information about serialization, on top of the static typing. But if you need something more advanced then you need to use `Field`.

There are however also the constrained types like `conlist` etc, which I'm not sure how they actually pass `mypy` checking.

**Comment by peterschutt** [comment]
Apologies for the drive-by comment, as I'm not a beanie user, but this looks like a use-case for `Annotated`.

```py
class MyModel(Document, BaseModel):
    indexed: Annotated[str, Indexed(...)]
```

A benefit of this is that other libraries that inspect types don't need to know anything about `Indexed` to know that the `indexed` field on this model is a `str` type.
