### ISSUE TITLE
[feature] Relations

### ISSUE THREAD

**Issue by roman-right** [roman-right/beanie#66]
If the field type is Document subclass, then only id should be stored there and the whole subdocument must be stored to the separated collection.

Example:

```python
class Window(Document):
  width: int
  height: int

class House(Document):
  address : str
  windows: List[Window]
  favorite_window: Window
```

Problems:
- fetching/ lazy fetching
- find by subfield. Example: `House.find(House.favorite_window.width == 1)`
- updates of the subdocument. Example: `house.set({House.favorite_window.width: 1})`

**Comment by jonwhittlestone** [comment]
+1

**Comment by zrothberg** [comment]
https://docs.mongoengine.org/apireference.html#mongoengine.fields.ReferenceField
https://pymongo.readthedocs.io/en/stable/api/bson/dbref.html

I assume we want to only do this explicitly instead of implicitly as it would make inheritance unworkable. Using the dbref field from pymongo has some advantages.  Mongoengine's implementation is probably the best reference point. We can make a parallel setup by implementing a subclass of Fields. This would let us catch it and create a similar flow to mongoengine. 


```python
class Window(Document):
  width: int
  height: int

class House(Document):
  address : str
  windows: List[Window]
  favorite_window: Window

class EmbeddedHouse(Document):
  address : str
  windows: List[Window] = Embed(...)
  favorite_window: Window = Embed(...)

```
May need some kind of argument to handle List. It would be hard to implement anything similar to Lazy Reference without freaking pydantic validation out.

**Comment by beratdogan** [comment]
Hi @roman-right - Any updates on this? Currently discussing to migrate our codebase using Beanie. Happy to contribute if you share your implementation thoughts to implement.

I'm stuck where/how should fetching/prefetching be done?

**Comment by beratdogan** [comment]
It's great to hear you're actively working on this. I'm curious about implementation of the fetching/prefetching - it should not cause N+1 fetching problems. As my research on MongoDB drivers and they are all making N+1 queries for fetching from related collections. Making `$lookup` aggregations or querying related docs at once by after collecting could help the performance.

Naming suggestion: `Referenced[]` might be more suitable name choice for this generic.

**Comment by roman-right** [comment]
Hey @beratdogan ,

Yes, for the pre-fetching it will use lookup aggregations. This part is ready for single relations and will be implemented for lists soon. There is a small limitation for now related to this. It will support only top-level fields for now. 
Later I'll try to support any field configuration.

**Comment by roman-right** [comment]
The feature is in PR. 
I'll play with naming a little this weekend and on Monday it will be released.
