### ISSUE TITLE
`Set` not supported?

### ISSUE THREAD

**Issue by Vovcharaa** [roman-right/beanie#77]
Is there any way to use `Set` as datatype in models?
![image](https://user-images.githubusercontent.com/10946676/123560808-49a81b80-d7ad-11eb-8e7d-7e6374c44c92.png)

**Comment by roman-right** [comment]
Hey @Vovcharaa ,

Yes. The thing is, JSON and respectively MongoDB doesn't support such entity as `set`. Lists only.

But for sure there are ways to use it. Some more ugly, some less.
The main idea is to map set to list because MongoDB will store it as a list anyway. As for me, the simplest way is to use pydantic pre-validators to be sure, that `set` was applied to the list from one side, and the set was converted to a list from the other side.

For this, you can follow the example:

```python
import asyncio
from typing import List

import motor.motor_asyncio
from pydantic import validator

from beanie import Document
from beanie import init_beanie


class Sample(Document):
    smth: List[int]

    @validator('smth')
    def remove_duplications(cls, v):
        if isinstance(v, set):
            return list(v)
        if isinstance(v, list):
            return list(set(v))
        raise TypeError("smth field must be of type list or set")

    class Collection:
        name = "test_set"


async def main():
    client = motor.motor_asyncio.AsyncIOMotorClient("MONGODB_DSN")
    await init_beanie(client.beanie_db, document_models=[Sample])
    sample = Sample(smth={1, 2, 3, 4})
    await sample.save()

    samples = await Sample.all().to_list()
    print(samples)


asyncio.run(main())
```

Another, more complex, but probably more beautiful way is to set up your own generic-based pydantic field type with internal logic. To do this, you can follow the doc: https://pydantic-docs.helpmanual.io/usage/types/#generic-classes-as-types

**Comment by Vovcharaa** [comment]
Thanks for response.

I am aware that JSON and MongoDB doesn't support `set`, but pydantic does and successfully encodes it in JSON Array and decodes back into `set`.
```python
from typing import Set
import pydantic


class Test(pydantic.BaseModel):
    test_set: Set[int]


example_set = {1, 1, 2, 4, 5, 7}  # pydantic also convert list and tuple to set if passed in the model

t_set = Test(test_set=example_set)
parsed = Test.parse_raw('{"test_set": [1, 2, 4, 5, 7, 7, 7, 7]}')

print(f"set in dict: {t_set.dict()}")
print(f"set encoded in json: {t_set.json()}")
print(f"loaded from json: {parsed.dict()}")
```
Output:
```
set in dict: {'test_set': {1, 2, 4, 5, 7}}
set encoded in json: {"test_set": [1, 2, 4, 5, 7]}
loaded from json: {'test_set': {1, 2, 4, 5, 7}}
```
Is there any problems for beanie to handle `set` like pydantic does?

**Comment by roman-right** [comment]
I see. Yes, this is a very good point.

Beanie uses `.dict()` method instead of `.json()` because it uses motor driver as an interface to mongodb, which accepts dictionaries. There are many advantages of this approach, but yes, I can not use pydantic's json serializer/deserializer for this.

I'm thinking about the feature - to add some custom pydantic fields to solve common mongodb-related issues (like Geo object, for example). I think `set` field also must be in this collection. Would this be helpful in your case?

**Comment by Vovcharaa** [comment]
From my point of view the best way to support such types is to create analog of `jsonable_encoder` function from fastapi.
Beanie can apply such function on model and receive mongodb compatible dict.

**Comment by Vovcharaa** [comment]
Example:
```python
from typing import Set
import pydantic
from fastapi.encoders import jsonable_encoder


class Test(pydantic.BaseModel):
    test_set: Set[int]


example_set = {1, 1, 2, 4, 5, 7}

t_set = Test(test_set=example_set)

print(f"jsonable_encoder function: {jsonable_encoder(t_set)}")
print(f"dict method: {t_set.dict()}")
```
Output:
```
jsonable_encoder function: {'test_set': [1, 2, 4, 5, 7]}
dict method: {'test_set': {1, 2, 4, 5, 7}}
```

**Comment by roman-right** [comment]
Good reference, thank you. 
Probably I'll implement something like this or add optional fields encoders/decoders.

Thank you for the ideas.

**Comment by roman-right** [comment]
I think, this issue could be closed
